# Generated by Django 5.2.17 on 2026-10-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OindrilaBirthday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaywish',
            name='guest_name',
            field=models.CharField(default='Oindrila', max_length=100),
            preserve_default=False,
        ),
    ]
